import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

const shell = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
const chat = readFileSync(resolve(import.meta.dirname, './chat-sidebar.tsx'), 'utf8')
const frame = readFileSync(resolve(import.meta.dirname, './shell-sidebar-frame.tsx'), 'utf8')

test('brand mascot lives at the corner; sidebar head is title plus collapse', () => {
  assert.match(shell, /BrandCornerMascot/)
  assert.match(shell, /variant="popover"/)
  assert.match(shell, /DockSessionMascot/)
  assert.match(frame, /data-testid="sidebar-collapse"/)
  assert.match(frame, /app-side-bar-head-brand/)
  assert.match(frame, /Biu Agent OS/)
  assert.match(chat, /ShellSidebarFrame/)
  assert.match(chat, /variant === 'popover'/)
  assert.match(chat, /dock-chat-sidebar/)
  assert.match(chat, /openOverlayComposer/)
  assert.match(chat, /sessionView.load\(item.id/)
  assert.doesNotMatch(chat, /SidebarBrandMascot/)
  const mascot = readFileSync(resolve(import.meta.dirname, '../../../web-mascot/src/web/brand-mascot.tsx'), 'utf8')
  assert.match(mascot, /brand-agent-menu/)
  assert.match(mascot, /data-dock-tip/)
  assert.match(mascot, /BrandAgentMenu/)
  assert.match(mascot, /brand-corner-mascot-toggle/)
  assert.match(mascot, /menu\?:/)
  assert.doesNotMatch(mascot, /brand-corner-dock/)
  assert.doesNotMatch(mascot, /brand-corner-chat-overlay/)
  assert.doesNotMatch(mascot, /onToggleOverlay/)
  assert.match(shell, /<BrandCornerMascot/)
  assert.match(shell, /ShellDockPins/)
  assert.doesNotMatch(shell, /activeModule === 'agent' \? null : \(/)
  assert.doesNotMatch(shell, /activeModule !== 'agent' &&/)
  assert.doesNotMatch(shell, /\{activeModule === 'agent' \? null/)
  assert.doesNotMatch(shell, /props.renderSlot\('corner-tools'\)/)
  assert.doesNotMatch(shell, /leading=\{activeModule === 'agent' \? null/)
  assert.doesNotMatch(shell, /onToggleOverlay/)
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.match(css, /\.brand-corner-mascot-btn\.is-active[\s\S]*?background:\s*transparent/)
  assert.match(css, /--brand-corner-clearance:\s*1\.25rem/)
  assert.match(css, /\.session-inspector\s*\{[^}]*padding-bottom:\s*var\(--brand-corner-clearance\)/s)
  assert.match(css, /\.brand-agent-menu\s*\{[^}]*width:\s*320px/s)
  assert.match(css, /\.brand-agent-menu\s*\{[^}]*border:\s*0/s)
  assert.match(css, /\.chat-sidebar-popover\s*\{/)
  assert.doesNotMatch(css, /\.os-dock-tile svg\s*\{/)
  assert.doesNotMatch(css, /\.brand-agent-menu svg[\s\S]{0,80}unset/)
  assert.match(css, /\.os-dock-tile \.brand-corner-mascot-btn svg\s*\{[^}]*width:\s*22px/s)
  assert.match(css, /\.chat-session-row-delete svg,\s*\.chat-session-row-star svg\s*\{[^}]*width:\s*16px/s)
  assert.doesNotMatch(css, /\.brand-agent-menu\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
  assert.match(css, /\.os-dock\s*\{/)
  assert.match(css, /\.os-dock-shelf-row\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1\)/s)
  assert.match(css, /\.os-dock-shelf-row\s*\{[^}]*backdrop-filter:\s*blur/s)
})
