import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

const shell = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
const title = readFileSync(resolve(import.meta.dirname, './chat-session-title.tsx'), 'utf8')
const chat = readFileSync(resolve(import.meta.dirname, './chat-sidebar.tsx'), 'utf8')
const frame = readFileSync(resolve(import.meta.dirname, './shell-sidebar-frame.tsx'), 'utf8')
const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')

test('brand mascot lives at the corner; sidebar head is title plus collapse', () => {
  assert.match(shell, /DockSessionMascot/)
  assert.match(title, /BrandCornerMascot/)
  assert.match(title, /variant="popover"/)
  assert.match(frame, /data-testid="sidebar-collapse"/)
  assert.match(frame, /app-side-bar-head-brand/)
  assert.match(frame, /SidebarBrandLockup/)
  assert.match(chat, /ShellSidebarFrame/)
  assert.match(chat, /variant === 'popover'/)
  assert.match(chat, /dock-chat-sidebar/)
  assert.match(chat, /openOverlayComposer/)
  assert.match(chat, /isChatPagePath/)
  assert.match(chat, /sessionView.load\(item.id/)
  assert.doesNotMatch(chat, /SidebarBrandMascot/)
  const mascot = readFileSync(resolve(import.meta.dirname, '../../../public-mascot/src/web/brand-mascot.tsx'), 'utf8')
  assert.doesNotMatch(mascot, /Biu Agent OS/)
  assert.match(mascot, /data-testid="brand-mascot"/)
  assert.match(mascot, /SidebarBrandLockup/)
  assert.match(mascot, /brand-agent-menu/)
  assert.match(mascot, /data-dock-tip/)
  assert.match(mascot, /BrandAgentMenu/)
  assert.match(mascot, /brand-corner-mascot-toggle/)
  assert.match(mascot, /menu\?:/)
  assert.match(mascot, /onToggle\?:/)
  assert.doesNotMatch(mascot, /brand-corner-dock/)
  assert.doesNotMatch(mascot, /brand-corner-chat-overlay/)
  assert.doesNotMatch(mascot, /onToggleOverlay/)
  assert.match(shell, /ShellDockPins/)
  assert.match(shell, /onToggle=\{/)
  assert.match(shell, /isChatPagePath\(location.pathname\)/)
  assert.match(shell, /setChatOverlay\(true\)/)
  assert.match(shell, /overlayOpen && !showCenter/)
  assert.match(shell, /activeModule === 'agent' && getChatOverlay\(\)/)
  assert.doesNotMatch(shell, /id: 'session'/)
  assert.doesNotMatch(shell, /kind: 'session'/)
  assert.doesNotMatch(shell, /activeModule === 'agent' \? null : \(/)
  assert.doesNotMatch(shell, /activeModule !== 'agent' &&/)
  assert.doesNotMatch(shell, /\{activeModule === 'agent' \? null/)
  assert.doesNotMatch(shell, /props.renderSlot\('corner-tools'\)/)
  assert.doesNotMatch(shell, /leading=\{activeModule === 'agent' \? null/)
  assert.doesNotMatch(shell, /onToggleOverlay/)
  assert.match(css, /\.sidebar-brand-lockup\s*\{/)
  assert.doesNotMatch(css, /\.sidebar-brand-name\s*\{/)
  assert.match(css, /\.brand-corner-mascot-btn\.is-active[\s\S]*?background:\s*transparent/)
  assert.match(css, /--brand-corner-clearance:\s*1\.25rem/)
  assert.match(css, /\.session-inspector\s*\{[^}]*padding-bottom:\s*var\(--brand-corner-clearance\)/s)
  assert.match(css, /\.brand-agent-menu\s*\{[^}]*width:\s*320px/s)
  assert.match(css, /\.brand-agent-menu\s*\{[^}]*border:\s*0/s)
  assert.match(css, /\.chat-sidebar-popover\s*\{/)
  assert.match(
    css,
    /\.chat-sidebar-popover \.chat-session-row\.is-active::before\s*\{[^}]*background:\s*rgba\(242,\s*241,\s*237,\s*0\.12\)/s,
  )
  assert.doesNotMatch(css, /\.os-dock-tile svg\s*\{/)
  assert.doesNotMatch(css, /\.brand-agent-menu svg[\s\S]{0,80}unset/)
  assert.doesNotMatch(css, /\.os-dock-tile \.brand-corner-mascot-btn svg\s*\{[^}]*width:\s*22px/s)
  assert.match(css, /\.os-dock-item > \.os-dock-tile > svg\s*\{[^}]*width:\s*22px/s)
  assert.match(css, /\.chat-session-row-delete svg,\s*\.chat-session-row-star svg\s*\{[^}]*width:\s*16px/s)
  assert.match(css, /\.brand-corner-cluster\s*\{[^}]*right:\s*16px/s)
  assert.match(css, /\.brand-corner-cluster\s*\{[^}]*bottom:\s*16px/s)
  assert.match(css, /\.brand-corner-cluster\s*\{[^}]*z-index:\s*200/s)
  assert.doesNotMatch(css, /\.os-dock \.brand-corner-cluster/)
  assert.match(css, /\.os-dock\s*\{/)
  assert.match(css, /\.os-dock-shelf-row\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1\)/s)
  assert.match(css, /\.os-dock-shelf-row\s*\{[^}]*backdrop-filter:\s*blur/s)
  assert.match(css, /\.chat-view-header-expand\s*\{[^}]*color:\s*#F0EFED/s)
  assert.match(css, /\.chat-view-header-expand:hover\s*\{[^}]*color:\s*#F0EFED/s)
  assert.match(css, /\.chat-view-header-expand\.is-active\s*\{[^}]*color:\s*#F0EFED/s)
  assert.match(css, /\.chat-view-project\s*\{[^}]*color:\s*#F0EFED/s)
  assert.match(css, /\.chat-view-session-title\s*\{[^}]*color:\s*#F0EFED/s)
  assert.match(css, /\.chat-overlay-panel \.chat-view-header\s*\{[^}]*color:\s*#F0EFED/s)
  assert.match(css, /\.inspector-tab\s*\{[^}]*color:\s*#F0EFED/s)
})

test('shell columns keep three tracks so sidebar and inspector can animate', () => {
  assert.match(css, /\.app-shell-agent\s*\{[^}]*transition:\s*grid-template-columns/s)
  assert.match(css, /\.app-shell-module\s*\{[^}]*transition:\s*grid-template-columns/s)
  assert.match(
    css,
    /\.app-shell-agent\s*\{[^}]*grid-template-columns:\s*var\(--sidebar-col, 0px\) minmax\(0, 1fr\) var\(--inspector-width, 0px\)/s,
  )
  assert.match(css, /\.app-shell-agent\.is-window-resizing\s*\{[^}]*transition:\s*none/s)
  assert.match(css, /\.app-shell-module\.is-window-resizing\s*\{[^}]*transition:\s*none/s)
  assert.doesNotMatch(css, /\.app-shell-agent\.is-sidebar-collapsed\s*\{/)
  assert.match(frame, /is-closed flex/)
  assert.match(css, /\.app-side-bar\s*\{[^}]*min-width:\s*0/s)
  assert.doesNotMatch(css, /\.app-side-bar\s*\{[^}]*min-width:\s*var\(--dsw-sidebar-min\)/s)
  assert.match(css, /\.app-side-bar\.is-closed,\s*\.session-inspector\.is-closed\s*\{[^}]*min-width:\s*0/s)
})
