import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

test('activity bar is gone; shared sidebar places switch agent and database', () => {
  const shell = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const frame = readFileSync(resolve(import.meta.dirname, './shell-sidebar-frame.tsx'), 'utf8')
  const chrome = readFileSync(resolve(import.meta.dirname, './shell-chrome.tsx'), 'utf8')
  const search = readFileSync(resolve(import.meta.dirname, './shell-search.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.doesNotMatch(shell, /data-testid="activity-rail-pin"/)
  assert.doesNotMatch(shell, /固定左侧导航/)
  assert.doesNotMatch(shell, /cordis\.rail\.pinned/)
  assert.doesNotMatch(shell, /app-activity-bar/)
  assert.doesNotMatch(shell, /ShellDockNav/)
  assert.doesNotMatch(shell, /shell-dock-nav/)
  assert.doesNotMatch(shell, /ShellChromeBar/)
  assert.match(frame, /ShellSidePlaces/)
  assert.match(chrome, /title="会话"/)
  assert.match(chrome, /ChatBubbleLeftRightIcon/)
  assert.match(chrome, /title="数据"/)
  assert.match(chrome, /title="设置"/)
  assert.doesNotMatch(chrome, /title="聊天"/)
  assert.doesNotMatch(chrome, /聊天面板/)
  assert.doesNotMatch(chrome, /数据面板/)
  assert.match(chrome, /chrome-search[\s\S]*chrome-notify[\s\S]*chrome-settings[\s\S]*chrome-chat-panel[\s\S]*chrome-data-panel/s)
  assert.match(chrome, /chromeIcon/)
  assert.doesNotMatch(chrome, /size-5 shrink-0/)
  assert.match(css, /\.shell-side-places \.app-side-actions-icon\s*\{[^}]*width:\s*16px/s)
  assert.match(css, /\.shell-side-places \.app-side-actions-icon\s*\{[^}]*height:\s*16px/s)
  assert.match(shell, /ShellSearchPanel/)
  assert.match(shell, /event.metaKey \|\| event.ctrlKey/)
  assert.match(shell, /event.key !== 'f'/)
  assert.match(shell, /addEventListener\('keydown', onKey, true\)/)
  assert.match(shell, /focusSeq=\{searchFocusSeq\}/)
  assert.match(search, /useLayoutEffect/)
  assert.match(search, /node\.focus\(\)/)
  assert.match(search, /openSearchHit/)
  assert.match(search, /biu:inspector-reveal/)
  assert.match(search, /searchHref/)
  assert.match(search, /event.shiftKey \? 'left' : 'right'/)
  assert.match(search, /useNavigate/)
  assert.match(search, /setChatOverlay\(false\)/)
  assert.match(search, /navigate\(href\)/)
  assert.match(search, /⇧↵ 左侧/)
  assert.match(search, /↵ 右侧/)
  assert.match(search, /\/api\/db\/list/)
  assert.match(search, /limit: String\(PER_KIND\)/)
  assert.match(search, /DEBOUNCE_MS/)
  assert.match(search, /AbortController/)
  assert.match(search, /path: '\/tasks'/)
  assert.match(search, /path: '\/pages'/)
  assert.match(search, /path: '\/plugins'/)
  assert.match(search, /path: '\/facets'/)
  assert.match(search, /ChatBubbleLeftRightIcon/)
  assert.match(css, /\.shell-search-dialog\s*\{[^}]*background:\s*#202020/s)
  assert.match(css, /\.shell-search-dialog\s*\{[^}]*border:\s*1px solid #383836/s)
  assert.match(css, /\.shell-search-dialog\s*\{[^}]*border-radius:\s*8px/s)
  assert.match(css, /\.shell-search-dialog\s*\{[^}]*width:\s*min\(672px, calc\(100vw - 32px\)\)/s)
  assert.match(css, /\.shell-search-dialog\s*\{[^}]*height:\s*min\(72vh, 640px\)/s)
  assert.doesNotMatch(search, /正在检索/)
  assert.match(search, /MagnifyingGlassIcon/)
  assert.match(search, /shell-search-field/)
  assert.match(search, /TagChip/)
  assert.match(search, /TagChips/)
  assert.match(css, /\.shell-search-scopes/)
  assert.match(chrome, /navigate\('\/database'\)/)
  assert.match(chrome, /setChatOverlay\(false\)/)
  assert.match(shell, /open=\{inspectorVisible\}/)
  assert.match(shell, /collections=\{collections\}/)
  assert.doesNotMatch(css, /\.app-activity-bar\s*\{/)
  assert.doesNotMatch(css, /\.app-rail-hover\s*\{/)
  assert.doesNotMatch(css, /\.os-dock\s*\{/)
})
