import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

test('activity bar is gone; chat chrome switches agent and database', () => {
  const shell = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const chrome = readFileSync(resolve(import.meta.dirname, './shell-chrome.tsx'), 'utf8')
  const nav = readFileSync(resolve(import.meta.dirname, './shell-dock-nav.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.doesNotMatch(shell, /data-testid="activity-rail-pin"/)
  assert.doesNotMatch(shell, /固定左侧导航/)
  assert.doesNotMatch(shell, /cordis\.rail\.pinned/)
  assert.doesNotMatch(shell, /app-activity-bar/)
  assert.match(shell, /ShellDockNav/)
  assert.match(shell, /ShellChromeBar/)
  assert.match(chrome, /聊天面板/)
  assert.match(chrome, /数据面板/)
  assert.match(chrome, /navigate\('\/database'\)/)
  assert.match(chrome, /setChatOverlay\(false\)/)
  assert.match(nav, /INSPECTOR_DOCK_TOOLS/)
  assert.match(nav, /requestInspectorOpen\(\)/)
  assert.match(nav, /requestInspectorTab\(item\.tabId\)/)
  assert.match(nav, /database:\/pages/)
  assert.match(nav, /tabId: 'database:\/facets'/)
  assert.match(nav, /title: '类型'/)
  assert.match(nav, /tabId: 'traj'/)
  assert.match(nav, /Icon: MapIcon/)
  assert.doesNotMatch(nav, /QueueListIcon/)
  assert.match(nav, /tabId: 'usage'/)
  assert.match(nav, /pruneOpenedForCollections/)
  assert.match(nav, /inspectorTabIsOpen/)
  assert.match(nav, /visible: collections == null \? true : alive/)
  assert.match(shell, /inspectorOpen=\{inspectorVisible\}/)
  assert.match(shell, /collections=\{collections\}/)
  assert.doesNotMatch(nav, /dock.patch\('composer'/)
  assert.doesNotMatch(css, /\.app-activity-bar\s*\{/)
  assert.doesNotMatch(css, /\.app-rail-hover\s*\{/)
})
