import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

test('activity bar is gone; shared sidebar places switch agent and database', () => {
  const shell = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const frame = readFileSync(resolve(import.meta.dirname, './shell-sidebar-frame.tsx'), 'utf8')
  const chrome = readFileSync(resolve(import.meta.dirname, './shell-chrome.tsx'), 'utf8')
  const search = readFileSync(resolve(import.meta.dirname, './shell-search.tsx'), 'utf8')
  const nav = readFileSync(resolve(import.meta.dirname, './shell-dock-nav.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.doesNotMatch(shell, /data-testid="activity-rail-pin"/)
  assert.doesNotMatch(shell, /固定左侧导航/)
  assert.doesNotMatch(shell, /cordis\.rail\.pinned/)
  assert.doesNotMatch(shell, /app-activity-bar/)
  assert.match(shell, /ShellDockNav/)
  assert.doesNotMatch(shell, /ShellChromeBar/)
  assert.match(frame, /ShellSidePlaces/)
  assert.match(chrome, /title="会话"/)
  assert.match(chrome, /title="数据"/)
  assert.match(chrome, /title="设置"/)
  assert.doesNotMatch(chrome, /title="聊天"/)
  assert.doesNotMatch(chrome, /聊天面板/)
  assert.doesNotMatch(chrome, /数据面板/)
  assert.match(chrome, /chrome-notify[\s\S]*chrome-settings/s)
  assert.match(chrome, /ShellSearchPanel/)
  assert.match(chrome, /createPortal/)
  assert.match(search, /\/api\/db\/list/)
  assert.match(search, /limit: String\(PER_KIND\)/)
  assert.match(search, /DEBOUNCE_MS/)
  assert.match(search, /AbortController/)
  assert.match(search, /path: '\/tasks'/)
  assert.match(search, /path: '\/pages'/)
  assert.match(search, /path: '\/plugins'/)
  assert.match(search, /path: '\/facets'/)
  assert.match(css, /\.shell-search-overlay\s*\{[^}]*justify-content:\s*center/s)
  assert.match(css, /\.shell-search-chip/)
  assert.match(chrome, /navigate\('\/database'\)/)
  assert.match(chrome, /setChatOverlay\(false\)/)
  assert.match(nav, /INSPECTOR_DOCK_TOOLS/)
  assert.match(nav, /requestInspectorOpen\(\)/)
  assert.match(nav, /requestInspectorTab\(item\.tabId\)/)
  assert.match(nav, /database:\/pages/)
  assert.match(nav, /tabId: 'database:\/facets'/)
  assert.match(nav, /title: '类型'/)
  assert.match(nav, /tabId: 'traj'/)
  assert.match(nav, /Icon: MapIcon/)
  assert.doesNotMatch(nav, /QueueListIcon/)
  assert.match(nav, /tabId: 'usage'/)
  assert.match(nav, /pruneOpenedForCollections/)
  assert.match(nav, /inspectorTabIsOpen/)
  assert.match(nav, /visible: collections == null \? true : alive/)
  assert.match(shell, /inspectorOpen=\{inspectorVisible\}/)
  assert.match(shell, /collections=\{collections\}/)
  assert.doesNotMatch(nav, /dock.patch\('composer'/)
  assert.doesNotMatch(css, /\.app-activity-bar\s*\{/)
  assert.doesNotMatch(css, /\.app-rail-hover\s*\{/)
})
