import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

test('database-ui ships one search menu for select and multi-select', () => {
  const menu = readFileSync(resolve(import.meta.dirname, './search-menu.tsx'), 'utf8')
  const select = readFileSync(resolve(import.meta.dirname, './cell-select.tsx'), 'utf8')
  const multi = readFileSync(resolve(import.meta.dirname, './cell-multi.tsx'), 'utf8')
  assert.match(menu, /function DbSearchMenu/)
  assert.match(menu, /db-search-menu/)
  assert.match(menu, /className="db-search-field"/)
  assert.match(menu, /\.db-search-field input\{[^}]*font-size:14px/)
  assert.match(menu, /\.db-search-field input::placeholder\{[^}]*font-size:14px/)
  assert.match(select, /<DbSearchMenu/)
  assert.match(multi, /<DbSearchMenu/)
  assert.match(multi, /TagChip/)
  assert.doesNotMatch(multi, /<input/)
  assert.doesNotMatch(multi, /db-cell-multi-input/)
  assert.match(menu, /\.db-cell-multi-box\{[^}]*display:flex/)
  assert.doesNotMatch(menu, /max-width:110px/)
  assert.match(menu, /\.db-cell-select-trigger\{[^}]*max-width:none/)
  assert.match(menu, /\.db-cell-select-trigger\{[^}]*background:transparent/)
  assert.match(menu, /\.db-cell-select-trigger\.is-empty\{[^}]*background:transparent/)
  assert.match(menu, /\.db-cell-multi-box:hover,\.db-cell-multi-box\[aria-expanded="true"\]\{[^}]*background:transparent/)
  assert.doesNotMatch(menu, /\.db-cell-multi-box\{[^}]*min-height:28px/)
  assert.doesNotMatch(menu, /\.db-cell-multi-input/)
  assert.doesNotMatch(multi, /搜索或添加/)
  assert.match(select, /chips/)
  assert.match(select, /<TagChip/)
  assert.match(multi, /multiple = true/)
  assert.match(multi, /<TagChip id=\{item\.value\}/)
  assert.match(multi, /is-empty/)
  assert.match(multi, /setOpen\(true\)/)
  assert.match(menu, /\.db-cell-multi\.is-empty\{[^}]*width:100%/)
  assert.match(menu, /\.db-cell-multi-box\.is-empty\{[^}]*width:100%/)
  assert.match(menu, /\.db-cell-multi-box\.is-empty\{[^}]*min-height:22px/)
  assert.doesNotMatch(select, /添加「/)
  assert.doesNotMatch(select, /未选择/)
  assert.match(select, /Boolean\(item\.value\)/)
})

test('datetime cell uses antd DatePicker, not datetime-local', () => {
  const picker = readFileSync(resolve(import.meta.dirname, './cell-datetime.tsx'), 'utf8')
  const index = readFileSync(resolve(import.meta.dirname, './index.ts'), 'utf8')
  const menu = readFileSync(resolve(import.meta.dirname, './search-menu.tsx'), 'utf8')
  assert.match(picker, /DatePicker/)
  assert.match(picker, /from 'antd'/)
  assert.match(picker, /darkAlgorithm/)
  assert.doesNotMatch(picker, /datetime-local/)
  assert.doesNotMatch(picker, /<DbMenu/)
  assert.match(index, /CellDateTime/)
  assert.match(menu, /\.db-datetime\{[^}]*color:var\(--dsw-label-2\)/)
  assert.match(picker, /format="YYYY\/MM\/DD HH:mm"/)
  assert.match(picker, /suffixIcon=\{null\}/)
  assert.doesNotMatch(picker, /CalendarDaysIcon/)
})
