/**
 * 粘性用户消息不得压过底部输入栏 / dock 悬浮控件。
 * sticky 的 z-index 写在 thread 组件 Tailwind 上（z-[1]）；
 * .chat-composer-dock 用更高的 z-index 保证机轴最顶。
 */
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = resolve(import.meta.dirname, '../../../..')

describe('composer dock stacking above sticky user', () => {
  it('isolates chat-stage and keeps composer-dock above sticky user z-index', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const shell = readFileSync(resolve(root, 'packages/web-app-shell/src/web/index.tsx'), 'utf8')
    const thread = readFileSync(resolve(root, 'packages/cap-chat/src/web/thread.tsx'), 'utf8')

    expect(css).toMatch(/--dsw-chat-font-size:\s*14px/)
    expect(css).toMatch(/--dsw-chat-composer-font-size:\s*16px/)
    expect(css).toMatch(/\.composer-tiptap\.is-readonly\s*\{[^}]*font-size:\s*var\(--dsw-chat-font-size\)/s)
    expect(css).toMatch(/\.chat-stage\s*\{[^}]*isolation:\s*isolate/s)
    expect(css).toMatch(/\.chat-composer-dock\s*\{[^}]*z-index:\s*20/s)
    expect(thread).toMatch(/sticky top-0 z-1 bg-transparent/)
    expect(thread).not.toMatch(/Running/)
    expect(thread).not.toMatch(/StatusRow/)
    expect(shell).toContain('chat-composer-dock')
    expect(shell).toContain('px-[80px]')
    expect(shell).toContain('pb-[calc(1rem+25px)]')
    expect(shell).not.toMatch(/md:px-8|lg:px-10/)
    expect(shell).not.toMatch(/bottom-0 z-\[2\]/)
  })

  it('compose-only overlay hides the reply thread until send', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/cap-chat/src/web/composer.tsx'), 'utf8')
    expect(css).toMatch(/\.chat-overlay-panel \{/)
    expect(css).not.toMatch(/\.chat-overlay-panel\.is-compose-only \.chat-overlay-thread/)
    expect(composer).toContain('revealOverlayThread')
    expect(composer).toContain('isComposerFocusPending')
    expect(composer).toContain('biu:composer-focus')
  })

  it('puts the session mascot after the header name, with the dock session picker', () => {
    const approvals = readFileSync(resolve(root, 'packages/cap-chat/src/web/approvals.tsx'), 'utf8')
    const title = readFileSync(resolve(root, 'packages/web-app-shell/src/web/chat-session-title.tsx'), 'utf8')
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const shell = readFileSync(resolve(root, 'packages/web-app-shell/src/web/index.tsx'), 'utf8')
    const overlayWin = readFileSync(resolve(root, 'packages/web-app-shell/src/web/overlay-window.tsx'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/cap-chat/src/web/composer.tsx'), 'utf8')
    expect(title).not.toContain('BrandCornerMascot')
    expect(title).toContain('chat-session-title-pop')
    expect(approvals).toContain('BrandCornerMascot')
    expect(approvals).toMatch(/renderSlot\('header-tools'\)[\s\S]*BrandCornerMascot/)
    expect(approvals).toContain('variant="popover"')
    expect(composer).not.toContain('CaretMascot')
    expect(composer).not.toContain('caret-mascot')
    expect(css).toMatch(/\.chat-dock-toolbar \.brand-corner-cluster\s*\{[^}]*position:\s*relative/s)
    expect(approvals).not.toContain('dock-session-mascot')
    expect(approvals).not.toContain('BrandAgentMenu')
    expect(approvals).not.toContain('setSessionPickerOpen')
    expect(shell).not.toMatch(/hit\.closest\('\.dock-agent-stack'\)/)
    expect(shell).toContain('OverlayChatWindow')
    expect(overlayWin).toContain('ChatPane')
    expect(overlayWin).toContain('chat-overlay-head')
    expect(overlayWin).not.toContain('startDrag')
    expect(overlayWin).not.toContain('chat-overlay-drag')
    expect(overlayWin).toContain('data-biu-ignore')
    expect(overlayWin).toContain("key: 'se'")
    expect(overlayWin).toContain('chat-overlay-resize-')
    expect(overlayWin).not.toContain('chat-overlay-layout-toggle')
    expect(overlayWin).not.toContain('layoutTools')
    expect(css).toMatch(/\.chat-overlay-panel \{/)
    expect(css).toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*#202020/s)
    expect(css).toMatch(/\.chat-overlay-panel\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*backdrop-filter:\s*blur/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*transparent/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*#191919/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1\)/s)
    expect(css).toMatch(/\.chat-overlay-head\s*\{[^}]*z-index:\s*30/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-overlay-thread\s*\{[^}]*padding-block:\s*0/s)
    expect(css).not.toMatch(/\.chat-overlay-panel \.chat-overlay-thread\s*\{[^}]*padding-bottom:\s*5\.5rem/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-stage\s*\{[^}]*padding-block:\s*0/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*position:\s*absolute/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*bottom:\s*20px/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*height:\s*auto/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*padding:\s*0 16px/s)
    expect(css).toMatch(/\.chat-overlay-panel \.composer-pill\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*background:\s*transparent/s)
    expect(css).toMatch(/\.chat-pane \.chat-composer-dock\s*\{[^}]*z-index:\s*10/s)
    expect(css).toMatch(/\.chat-pane-embed\s*\{[^}]*background:\s*#191919/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\.is-autohide/)
    expect(css).toMatch(/\.composer-pill/)
    expect(css).toMatch(/\.composer-pill\s*\{[^}]*background:\s*#202020/s)
    expect(css).not.toMatch(/\.composer-pill\s*\{[^}]*backdrop-filter:\s*blur/s)
    expect(css).not.toMatch(/\.composer-pill\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1\)/s)
    expect(css).not.toMatch(/\.composer-pill\s*\{[^}]*background:\s*var\(--dsw-sidebar\)/s)
  })

  it('squares the composer when pick chips are present', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/cap-chat/src/web/composer.tsx'), 'utf8')
    expect(composer).toMatch(/has-chips/)
    expect(css).toMatch(/\.composer-pill\.has-chips[\s\S]*border-radius:\s*var\(--dsw-radius-bubble\)/)
  })

  it('uses facet tones for pick chips and the clear-context control, not the plus', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const chip = readFileSync(resolve(root, 'packages/cap-pick/src/web/chip.tsx'), 'utf8')
    const node = readFileSync(resolve(root, 'packages/cap-chat/src/web/composer-pick-node.tsx'), 'utf8')
    const approvals = readFileSync(resolve(root, 'packages/cap-chat/src/web/approvals.tsx'), 'utf8')
    expect(css).toMatch(/\.project-chip\.project-chip-clear-ctx\s*\{[^}]*background:\s*transparent/s)
    expect(css).toMatch(/\.project-chip-hist-bar\s*\{[^}]*color-mix\(in srgb, var\(--biu-tag, #d9730d\) 22%, transparent\)/s)
    expect(css).toMatch(/\.project-chip\.project-chip-clear-ctx\s*\{[^}]*color:\s*#d9730d/s)
    expect(css).toMatch(/\.composer-plus\s*\{[^}]*background:\s*transparent/s)
    expect(css).toMatch(/\.composer-plus\s*\{[^}]*color:\s*#F0EFED/s)
    expect(css).toMatch(/\.composer-model-trigger\s*\{[^}]*color:\s*#F0EFED/s)
    expect(css).toMatch(/\.project-chip\s*\{[^}]*color:\s*#F0EFED/s)
    expect(css).toMatch(/\.dock-icon-btn\s*\{[^}]*color:\s*#F0EFED/s)
    expect(css).not.toMatch(/\.composer-plus\s*\{[^}]*color:\s*#e255a1/s)
    expect(approvals).toMatch(/project-chip-clear-ctx/)
    expect(approvals).toMatch(/project-chip-hist-bar/)
    expect(approvals).toMatch(/histRatio \* 100/)
    expect(css).toMatch(/\.project-chip\.project-chip-clear-ctx\s*\{[^}]*border:\s*1px solid #d9730d/s)
    expect(css).toMatch(/\.project-chip\.project-chip-pick-toggle\s*\{[^}]*border:\s*1px solid #5b9fd6/s)
    expect(css).toMatch(/\.project-chip-clear-ctx\[data-dock-tip\]::after\s*\{[^}]*border-color:\s*#d9730d/s)
    expect(css).toMatch(/\.project-chip-pick-toggle\[data-dock-tip\]::after\s*\{[^}]*border-color:\s*#5b9fd6/s)
    expect(css).toMatch(/\.project-chip\.project-chip-pick-toggle\s*\{[^}]*color:\s*#5b9fd6/s)
    expect(css).toMatch(/\.project-chip\.project-chip-pick-toggle\.is-active\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--biu-tag, #5b9fd6\) 22%, transparent\)/s)
    expect(css).toMatch(/\[data-dock-tip-at='ne'\]::after/)
    expect(approvals).toMatch(/data-dock-tip-at="ne"/)
    expect(approvals).not.toContain('待确认工具 · 先处理后再发')
    expect(approvals).toContain('dock-approval-mark')
    expect(approvals).toMatch(/data-dock-tip="待确认"/)
    expect(approvals).toContain('dock-approval-card-actions')
    expect(approvals).toContain('dock-approval-card-head')
    expect(css).toMatch(/\.dock-approval-card\s*\{[^}]*min-height:\s*148px/s)
    expect(css).toMatch(/\.dock-approval-card-actions\s*\{[^}]*position:\s*absolute/s)
    expect(css).toMatch(/\.dock-approval-card-actions\s*\{[^}]*right:\s*12px/s)
    expect(css).toMatch(/\.dock-approval-card-actions\s*\{[^}]*bottom:\s*8px/s)
    expect(css).toMatch(/\.composer-tool-chip\.is-pick,\s*\n\.user-pick-chip\s*\{[^}]*--biu-tag/s)
    expect(chip).toMatch(/pickKindTone/)
    expect(chip).toMatch(/tagTone\(canonicalPickKind\(kind\)\)/)
    expect(chip).toMatch(/onRemove/)
    expect(chip).toMatch(/biu-tag-x/)
    expect(node).toMatch(/<PickChip pick=/)
    expect(node).toMatch(/onRemove=\{remove\}/)
  })

  it('uses the specified chrome palette and pick highlight', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    expect(css).toMatch(/--dsw-bg:\s*#191919/)
    expect(css).toMatch(/--dsw-placeholder:\s*#5F5F5A/)
    expect(css).toMatch(/::placeholder\s*\{[^}]*color:\s*var\(--dsw-placeholder\)/)
    expect(css).toMatch(/--dsw-sidebar:\s*#202020/)
    expect(css).toMatch(/--dsw-hover:\s*#2c2c2c/)
    expect(css).toMatch(/--dsw-sidebar-fg:\s*#bcbab6/)
    expect(css).toMatch(/--dsw-sidebar-fg-active:\s*#f0efed/)
    expect(css).toMatch(/--dsw-pick:\s*#5b9fd6/)
    expect(css).toMatch(/--dsw-pick-fill:\s*color-mix\(in srgb, #5b9fd6 22%, transparent\)/)
    expect(css).toMatch(/--dsw-pick-stroke:\s*color-mix\(in srgb, #5b9fd6 40%, transparent\)/)
    expect(css).toMatch(/\.pick-overlay-box[\s\S]*background:\s*var\(--dsw-pick-fill\)/)
    expect(css).toMatch(/\.pick-overlay-marquee[\s\S]*background:\s*var\(--dsw-pick-fill\)/)
  })

  it('uses facet orange fill on clear-context only when there is history', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const approvals = readFileSync(resolve(root, 'packages/cap-chat/src/web/approvals.tsx'), 'utf8')
    expect(css).toMatch(/\.project-chip-hist-bar\s*\{[^}]*color-mix\(in srgb, var\(--biu-tag, #d9730d\) 22%, transparent\)/s)
    expect(approvals).toMatch(/project-chip-hist-bar/)
    expect(css).toMatch(/\.chat-pane\s*\{[^}]*--dsw-ok:\s*#448361/s)
    expect(css).toMatch(/\.chat-pane\s*\{[^}]*--dsw-danger:\s*#c4554d/s)
    expect(css).toMatch(/\.tool-call-status\.is-ok\s*\{[^}]*color:\s*#448361/s)
    expect(css).not.toMatch(/\.tool-call-status\.is-ok\s*\{[^}]*color-mix\(in srgb, #448361 22%, transparent\)/s)
    expect(css).toMatch(/\.tool-call-status\.is-fail\s*\{[^}]*color:\s*#c4554d/s)
    expect(css).not.toMatch(/\.tool-call-status\.is-fail\s*\{[^}]*color-mix\(in srgb, #c4554d 22%, transparent\)/s)
    expect(css).toMatch(/\.tool-call-chevron\.is-ok\s*\{[^}]*color:\s*#448361/s)
    expect(css).toMatch(/\.tool-call-chevron\.is-fail\s*\{[^}]*color:\s*#c4554d/s)
    expect(css).toMatch(/\.tool-call-head\.is-open\.is-ok::before[\s\S]*#448361 22%/)
    expect(css).toMatch(/\.tool-call-head\.is-open\.is-fail::before[\s\S]*#c4554d 22%/)
    expect(css).toMatch(/\.tool-call-inspect\s*\{[^}]*opacity:\s*0/s)
    expect(css).toMatch(/\.tool-call-head:hover \.tool-call-inspect/s)
    expect(css).toMatch(/\.traj-usage-ring\.is-cache\s*\{[^}]*color:\s*#448361/s)
    expect(css).toMatch(/\.traj-usage-ring\.is-hist\s*\{[^}]*color:\s*#d9730d/s)
    const usage = readFileSync(resolve(root, 'packages/cap-chat/src/web/usage-inline.tsx'), 'utf8')
    expect(usage).toMatch(/TAG_TONE_GREEN/)
    expect(usage).toMatch(/TAG_TONE_ORANGE/)
    expect(usage).toMatch(/stroke="currentColor"/)
    expect(approvals).toContain('上下文占输入文字')
    expect(approvals).not.toMatch(/清空上下文 · 历史/)
    expect(approvals).not.toMatch(/backgroundColor/)
    expect(approvals).not.toMatch(/<ChatLiveMetrics/)
    expect(approvals).toMatch(/typeof props.renderSlot === 'function'/)
    expect(approvals).toMatch(/aria-label="清空上下文"[\s\S]*renderSlot\('header-tools'\)/)
  })

  it('paints inspector trajectory and usage on the same sidebar token as the left rail', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    expect(css).toMatch(/\.traj-root\s*\{[^}]*background:\s*var\(--dsw-sidebar\)/s)
    expect(css).toMatch(/\[data-testid='session-inspector'\] \.usage-panel\s*\{[^}]*background:\s*var\(--dsw-sidebar\)/s)
    expect(css).toMatch(/\.session-inspector\s*\{[^}]*background:\s*#191919/s)
    expect(css).toMatch(/\.session-inspector \.app-side-bar-head\s*\{[^}]*background:\s*#191919/s)
    expect(css).toMatch(/\[data-testid='session-inspector'\] \.traj-root[\s\S]*background:\s*var\(--dsw-sidebar\)/)
  })

  it('keeps pick chips from inheriting the composer line-height', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    expect(css).toMatch(/\.composer-inline-chip\s*\{[^}]*align-items:\s*center/s)
    expect(css).toMatch(/\.composer-inline-chip\s*\{[^}]*vertical-align:\s*middle/s)
    expect(css).toMatch(/\.composer-inline-chip\s*\{[^}]*line-height:\s*1/s)
    expect(css).toMatch(/\.composer-tool-chip\.is-pick,\s*\n\.user-pick-chip\s*\{[^}]*line-height:\s*20px/s)
    expect(css).toMatch(/\.pick-kind-icon\s*\{[^}]*display:\s*block/s)
    expect(css).toMatch(
      /\.composer-pill\.has-chips \.composer-tiptap p,\s*\n\.composer-tiptap\.is-readonly p \{\s*line-height:\s*1\.45/,
    )
  })

  it('uses Tiptap for inline pick chips in the composer', () => {
    const composer = readFileSync(resolve(root, 'packages/cap-chat/src/web/composer.tsx'), 'utf8')
    const node = readFileSync(resolve(root, 'packages/cap-chat/src/web/composer-pick-node.tsx'), 'utf8')
    expect(composer).toMatch(/useEditor/)
    expect(composer).toMatch(/composerDocExtensions/)
    expect(composer).toMatch(/EditorContent/)
    expect(composer).toMatch(/insertPickChips/)
    expect(node).not.toMatch(/ReactNodeViewRenderer/)
    expect(node).toMatch(/queueMicrotask/)
  })
})
