import { test } from 'vitest'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { sessionsChrome } from './sessions-chrome.tsx'

const chrome = sessionsChrome({ slotProps: {} })

test('session table uses mascot as the standalone icon property, title is just the label', () => {
  assert.equal(typeof chrome.Title, 'function')
  assert.equal(typeof chrome.Icon, 'function')
  const src = readFileSync(resolve(import.meta.dirname, './sessions-chrome.tsx'), 'utf8')
  assert.match(src, /function SessionIcon/)
  assert.match(src, /size=\{20\}/)
  assert.match(src, /SidebarMascot/)
  assert.match(src, /resolveSessionMascot/)
  assert.match(src, /sessions-title-label/)
  assert.doesNotMatch(src, /className="sessions-title"/)
  assert.equal(typeof chrome.cells?.mascotShape, 'function')
  assert.equal(typeof chrome.Content, 'function')
  assert.match(src, /ChatPane/)
  assert.match(src, /ChatStage/)
  assert.match(src, /embed/)
  assert.match(src, /session-outline-host/)
  assert.match(src, /createPortal/)
  assert.match(src, /fsdb-right/)
  assert.match(src, /inset:0/)
  assert.match(src, /left:8px/)
  assert.match(src, /top:50%/)
  assert.doesNotMatch(src, /50cqh/)
  assert.doesNotMatch(src, /container-type/)
  assert.match(src, /deriveChatOutline/)
  assert.match(src, /\/api\/sessions\/\$\{sessionId\}/)
  assert.match(src, /session-composer-host/)
  assert.match(src, /session-record-chat-host/)
  assert.match(src, /fsdb-fileview:has\(\.chat-pane-embed\)/)
  assert.match(src, /ChatComposer/)
  assert.match(src, /boundSessionId/)
  assert.match(src, /snapshot\.onMessage\('session'/)
  assert.match(src, /upsertSessionEvent/)
  assert.match(src, /stageRef/)
  assert.match(src, /scrollTop = el\.scrollHeight/)
  assert.doesNotMatch(src, /sessionView\.load/)
  assert.doesNotMatch(src, /SlotOutlet/)
  assert.doesNotMatch(src, /name="composer"/)
  assert.match(src, /ApprovalsRail/)
  assert.match(src, /ChatConfigBanner/)
  assert.match(src, /ChatLiveHud/)
  assert.match(src, /boundSessionId={sessionId}/)
  assert.match(src, /bottom:0;z-index:20;padding:0 60px calc\(1rem \+ 25px\)/)
  const composer = readFileSync(resolve(import.meta.dirname, './composer.tsx'), 'utf8')
  assert.match(composer, /boundSessionId/)
  assert.match(composer, /\/api\/sessions\/\$\{boundSessionId\}\/messages/)
  assert.match(composer, /wait: false/)
  assert.doesNotMatch(composer, /sessionView\.load/)
  assert.doesNotMatch(src, /session-record-log/)
  const index = readFileSync(resolve(import.meta.dirname, './index.ts'), 'utf8')
  assert.match(index, /decorate\('\/sessions', sessionsChrome/)
})
