import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const trail = readFileSync(resolve(import.meta.dirname, './crumb-trail.tsx'), 'utf8')
const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
const nav = readFileSync(resolve(import.meta.dirname, './sidebar-nav.ts'), 'utf8')
const style = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')

describe('顶栏三级标题', () => {
  it('中间顶栏点标题出菜单', () => {
    expect(trail).toContain("aria-haspopup={canPick ? 'menu' : undefined}")
    expect(trail).toContain('allowMenu')
    expect(trail).toContain('icon={crumb.icon ?? current?.icon}')
    expect(trail).toContain('emoji={current?.emoji ?? crumb.emoji}')
    expect(trail).toContain('tableCrumb?.icon')
    expect(nav).toContain('builtinAllViewId(target.collection)')
    expect(browser).not.toContain('{ catalog: true }')
    expect(trail).not.toContain("crumb.kind === 'collection' && index < crumbs.length - 1")
    expect(trail).toContain('crumbButtonAction(crumb')
    expect(trail).toContain('lockRootCrumb')
    expect(browser).not.toContain('lockRootCrumb')
    expect(browser).toContain('<CrumbTrail')
    const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
    expect(page).toMatch(/onOpenView=\{\(viewId\) => go\(\{ collection: currentPath, viewId \}\)/)
    expect(trail).toContain('createPortal')
    expect(trail).toContain('data-fsdb-crumb-menu')
    expect(trail).toContain('fsdb-crumb-search')
    expect(trail).toContain('添加视图')
    expect(trail).toContain('新建记录')
    expect(trail).toContain('onCreate')
    expect(trail).toContain('openMenu')
    expect(trail).toContain('event.currentTarget.getBoundingClientRect()')
    expect(trail).toContain('onPointerDown')
    expect(trail).toContain('autoFocus')
    expect(trail).not.toContain('setTimeout')
    expect(trail).not.toContain('useLayoutEffect')
    expect(trail).toContain('listenOutsideDismiss')
    expect(browser).not.toContain('setCrumbOpen')
    expect(browser).not.toContain('openId={crumbOpen}')
    expect(browser).not.toContain('if (!searchRef.current?.contains(target) && !query) setSearchOpen(false)')
    expect(trail).not.toContain('data-testid="crumb-expand"')
    expect(style).not.toContain('.fsdb-crumb-expand{position:absolute')
    expect(browser).toContain('<CrumbTrail')
  })

  it('中间顶栏面包屑字重和颜色与侧栏标题对齐', () => {
    expect(style).toContain('.fsdb-crumb-btn{display:inline-flex')
    expect(style).toMatch(/\.fsdb-crumb-btn\{[^}]*color:#F0EFED/)
    expect(style).toMatch(/\.fsdb-crumb-btn\{[^}]*font-weight:600/)
    expect(style).toMatch(/\.fsdb-crumb-option\{[^}]*font-weight:600/)
  })

  it('改视图名会先写入缓存再通知面包屑', () => {
    expect(browser).toMatch(/rememberViews\(path, listed\)[\s\S]*localStorage\.setItem\(viewsKey\(path\)[\s\S]*fsdb:change/)
    expect(browser).toContain("window.dispatchEvent(new Event('fsdb:crumb-labels'))")
    expect(browser).toContain('rememberRecords')
    expect(browser).toContain('crumbRecordLabel')
  })
})
