import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
const detail = readFileSync(resolve(import.meta.dirname, './record-detail.tsx'), 'utf8')

test('data sidebar brand sits left with a collapse control on the right', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  assert.match(sidebar, /app-side-bar-head-brand/)
  assert.match(sidebar, /SidebarBrandLockup/)
  assert.match(sidebar, /data-testid="sidebar-collapse"/)
  assert.doesNotMatch(sidebar, /SidebarBrandMascot/)
  assert.match(browser, /onCollapse=\{toggleViewsOpen\}/)
  assert.match(browser, /biu:toggle-shell-sidebar/)
  assert.match(sidebar, /shell-module-sidebar/)
})

test('user and system collection sections fold independently', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const fold = readFileSync(resolve(import.meta.dirname, '../../../public-ui/src/sidebar-fold.tsx'), 'utf8')
  assert.match(sidebar, /const \[userOpen, setUserOpen\] = useState\(true\)/)
  assert.match(sidebar, /const \[systemOpen, setSystemOpen\] = useState\(true\)/)
  assert.match(sidebar, /onClick=\{\(\) => setUserOpen\(\(prev\) => !prev\)\}/)
  assert.match(sidebar, /onClick=\{\(\) => setSystemOpen\(\(prev\) => !prev\)\}/)
  assert.match(sidebar, /<SidebarFold/)
  assert.match(fold, /function SidebarFold/)
  assert.match(fold, /className=\{\`sidebar-fold\$\{open \? ' is-open' : ''\}/)
  assert.doesNotMatch(sidebar, /sidebar-session-list min-w-0 \$\{open \? '' : 'hidden'\}/)
  assert.doesNotMatch(sidebar, /\{userOpen \?/)
  assert.doesNotMatch(sidebar, /\{systemOpen \?/)
  assert.doesNotMatch(sidebar, /\{favOpen \?/)
})

test('grouped views nest a foldable group layer in the sidebar', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.match(sidebar, /groupRecords\(state\.items, state\.schema, view\.groupBy\)/)
  assert.match(sidebar, /data-testid="sidebar-view-group"/)
  assert.match(sidebar, /fsdb-view-preview-records/)
  assert.match(css, /\.fsdb-view-preview-records \.chat-session-row > \.chat-session-row-main/)
})

test('table and view rows only expand from the fold column', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.match(css, /\.sidebar-fold\s*\{[^}]*grid-template-rows:\s*0fr/s)
  assert.match(css, /\.sidebar-fold\.is-open\s*\{[^}]*grid-template-rows:\s*1fr/)
  assert.match(css, /\.sidebar-fold\.is-animating\s*\{[^}]*transition:\s*grid-template-rows/)
  assert.doesNotMatch(css, /\.sidebar-fold\s*\{[^}]*transition:\s*grid-template-rows/s)
  assert.match(sidebar, /const listed = path === collectionPath \? views : loadViews\(path\)/)
  assert.match(sidebar, /viewsForRegisteredCollection\(path, tables, listed\)/)
  assert.doesNotMatch(sidebar, /catalog: true/)
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.doesNotMatch(page, /opts\?\.catalog/)
  assert.match(page, /go\(\{ collection: path, viewId: viewId \?\? builtinAllViewId\(path\) \}\)/)
  assert.doesNotMatch(page, /recordsPath=\{recordsPath\}/)
  assert.doesNotMatch(page, /isCollectionHub/)
  assert.doesNotMatch(page, /go\(\{ collection: path, viewId: viewId \?\? defaultViewId\(path\) \}\)/)
  assert.match(sidebar, /setUserOpen/)
  assert.match(sidebar, /setSystemOpen/)
  assert.doesNotMatch(sidebar, /onClick=\{\(\) => setDataOpen/)
  assert.doesNotMatch(sidebar, /useState<Record<string, boolean>>\(\(\) => \(\{ \[table\.path\]: true \}\)\)/)
  assert.doesNotMatch(sidebar, /setOpenTables\(\(prev\) => \(\{ \.\.\.prev, \[path\]: true \}\)\)/)
  assert.match(sidebar, /用户数据/)
  assert.match(sidebar, /系统数据/)
  assert.match(sidebar, /data-testid="sidebar-user-collections"/)
  assert.match(sidebar, /data-testid="sidebar-system-collections"/)
  assert.match(sidebar, /data-collection-kind/)
  assert.match(sidebar, /isSystemCollection/)
  assert.match(sidebar, /className="sidebar-add"/)
  assert.match(sidebar, /onAddView\(table\.path\)/)
  assert.match(css, /\.sidebar-group-fold:hover \.sidebar-group-fold-chevron/)
  assert.doesNotMatch(css, /\.chat-session-row:hover \.sidebar-group-fold-chevron/)
})

test('sidebar records paint detail immediately without reloading the view', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.match(browser, /flushSync\(\(\) => \{\s*setOpenDetailId\(recordId\)/)
  assert.match(browser, /if \(row\) setDetailRow\(row\)/)
  assert.match(browser, /onOpenRecord\?\.\(recordId, view\.id, path\)/)
  assert.match(browser, /if \(path === collectionPath\) \{\s*applyView\(view\)/)
  assert.doesNotMatch(browser, /onOpenRecord=\{\(path, view, recordId\) => \{\s*selectView/)
  assert.match(page, /viewId: viewId \?\? viewFromRoute/)
  assert.match(page, /parsed\.kind === 'collection-view' \|\| parsed\.kind === 'record' \? parsed\.viewId/)
  assert.match(browser, /!detailId \?/)
  assert.match(sidebar, /onOpenRecord\?\.\(row\.id, row\)/)
  assert.match(sidebar, /event.stopPropagation\(\)/)
  const emoji = readFileSync(resolve(import.meta.dirname, '../../../public-ui/src/emoji-board.tsx'), 'utf8')
  assert.match(emoji, /function RecordEmojiBoard/)
  assert.match(emoji, /className="fsdb-emoji-picker is-fixed"/)
  assert.match(sidebar, /fsdb-record-emoji/)
  assert.match(css, /\.fsdb-emoji-picker \{[^}]*border:\s*0/s)
  assert.match(css, /\.fsdb-emoji-picker \{[^}]*background:\s*#191919/s)
})

test('table title opens record from the title-side button', () => {
  assert.match(browser, /data-testid="record-title-open"/)
  assert.match(browser, /data-testid="record-title-split"/)
  assert.match(browser, /showRecordInInspector\(collectionPath, row.id\)/)
  assert.match(browser, /className="tasks-title-open"/)
  assert.match(browser, /tasks-title-aside/)
  assert.match(browser, /tasks-tree-count/)
  assert.match(browser, /kidCount/)
  assert.match(browser, /tasks-tree-toggle is-empty/)
  assert.match(browser, /hasTreeLinks\(items, parentKey\)/)
  assert.match(browser, /const treeOn = treeable && showTree/)
  assert.match(browser, /const tree = openDetail && treeOn/)
  assert.match(browser, /openRow\(row\)/)
  assert.match(browser, /chrome\?\.openRow/)
  assert.doesNotMatch(browser, /catalogRowOpenTarget/)
  assert.doesNotMatch(browser, /tagRowOpenTarget/)
  assert.doesNotMatch(browser, /stampRowOpenTarget/)
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.match(page, /viewsChrome/)
  assert.doesNotMatch(page, /openRegisteredRow/)
  assert.doesNotMatch(page, /onOpenRow=\{/)
  assert.doesNotMatch(page, /addSchemaTagField/)
  const nav = readFileSync(resolve(import.meta.dirname, './collection-nav.ts'), 'utf8')
  assert.match(nav, /listViews/)
  assert.doesNotMatch(nav, /catalogRowOpenTarget/)
  assert.doesNotMatch(nav, /tagRowOpenTarget/)
  assert.doesNotMatch(nav, /stampRowOpenTarget/)
  assert.doesNotMatch(browser, /onAddField/)
  assert.doesNotMatch(browser, /<AddProperty/)
  assert.match(browser, /const lockedSource = catalogLocks.tablePath/)
  assert.doesNotMatch(browser, /recordPick\(row\)\} onClick=\{\(\) => setDetailId\(row\.id\)\}/)
})

test('title cell row tools skip the overflow action menu', () => {
  assert.match(browser, /if \(place === 'row'\)/)
  assert.match(browser, /rowShown\.map\(renderOne\)/)
})

test('deletable tables can pick rows and bulk-delete next to refresh', () => {
  assert.match(browser, /data-testid="fsdb-bulk-delete"/)
  assert.match(browser, /kind: 'delete-records'/)
  assert.match(browser, /className=\{\`fsdb-boolbtn fsdb-row-check\$\{on \? ' is-on' : ''\}\`\}/)
  assert.match(browser, /<BoolBox/)
  const boolBox = readFileSync(resolve(import.meta.dirname, '../../../public-ui/src/bool-box.tsx'), 'utf8')
  assert.match(boolBox, /fsdb-boolbox/)
  assert.doesNotMatch(browser, /type="checkbox"/)
  assert.match(browser, /const canDelete = Boolean\(schema\?\.records\?\.delete\) && !subsetLocked/)
  assert.match(browser, /if \(field.writable && kind !== 'file'\)/)
  assert.match(browser, /<FieldEditor/)
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  assert.match(cells, /if \(kind === 'select' \|\| kind === 'multi-select'\)/)
  assert.match(cells, /<TokenMultiSelect/)
  assert.match(cells, /multiple=\{kind === 'multi-select'\}/)
  assert.doesNotMatch(cells, /<CellSelect/)
  const schemaUi = readFileSync(resolve(import.meta.dirname, './schema-field.tsx'), 'utf8')
  assert.match(schemaUi, /<CellMulti/)
  assert.doesNotMatch(schemaUi, /function TagPicker/)
  assert.doesNotMatch(cells, /placeholder=\{fieldKey\}/)
  assert.doesNotMatch(cells, /YYYY-MM-DDTHH:mm/)
  assert.doesNotMatch(cells, /datetime-local/)
  assert.match(cells, /<CellDateTime/)
  assert.match(cells, /<MediaField/)
  assert.doesNotMatch(cells, /placeholder=\{kind === 'image'/)
  const media = readFileSync(resolve(import.meta.dirname, './cell-media.tsx'), 'utf8')
  assert.doesNotMatch(media, /或填写链接/)
  assert.match(media, /kind === 'url'/)
  assert.match(media, /type="file"/)
  assert.match(media, /inputRef\.current\?\.click\(\)/)
  assert.match(media, /item\.type\.startsWith\('image\/'\)/)
  assert.match(media, /function AttachmentFile/)
  assert.match(media, /ArrowDownTrayIcon/)
  assert.match(media, /download=\{file\.name\}/)
  assert.match(media, /onRemove=\{\(\) => onCommit\(''\)\}/)
  assert.match(browser, /fsdb-file-tools/)
  assert.match(media, /file\.name/)
  assert.match(media, /file\.lastModified/)
  assert.match(media, /imagesRef\.current/)
  assert.match(media, /document\.addEventListener\('paste', onPaste, true\)/)
  assert.match(browser, /fieldDraftValue\(field, row\[key\]\)/)
  assert.match(browser, /const Custom = chrome\?\.cells\?\.\[key\][\s\S]*if \(field.writable && kind !== 'file'\)/)
  assert.match(browser, /key && field\?\.writable \?/)
  assert.match(browser, /cellUsesPop/)
  assert.match(browser, /CELL_POP_DRAG_PX/)
  assert.match(browser, /start\?\.dragged/)
  assert.match(browser, /onClick=\{\(event\) => \{[\s\S]*?setCellPop\(cellUsesPop/)
  assert.match(browser, /cellPopPtrRef\.current = \{ x: event\.clientX, y: event\.clientY, dragged: false \}/)
  assert.match(browser, /if \(surface === 'table'\)/)
  assert.match(browser, /<CellPopDraft/)
  const popDraft = readFileSync(resolve(import.meta.dirname, './cell-pop-draft.tsx'), 'utf8')
  assert.doesNotMatch(popDraft, /提交/)
  assert.doesNotMatch(popDraft, /取消/)
  assert.match(popDraft, /fsdb-cell-pop-tags/)
  assert.match(popDraft, /fsdb-cell-pop-text/)
  assert.match(popDraft, /kind === 'facet'/)
  assert.match(popDraft, /retagSchemaValue\(parsed, resolved\)/)
  assert.match(popDraft, /sameDraft\(next, initial\)/)
  assert.doesNotMatch(popDraft, /SchemaFieldEditor/)
  assert.doesNotMatch(browser, /if \(pop\) return <DefaultCell field=\{field\} value=\{row\[key\]\}/)
  const pop = readFileSync(resolve(import.meta.dirname, './cell-pop.tsx'), 'utf8')
  assert.match(pop, /top: rect\.top/)
  assert.match(pop, /left: rect\.left/)
  assert.doesNotMatch(pop, /rect\.bottom \+ 4/)
  assert.match(pop, /kind !== 'action' && kind !== 'file' && kind !== 'boolean'/)
  assert.match(browser, /kind === 'boolean'/)
  assert.match(browser, /<BoolCell on=\{on\} writable onToggle/)
  assert.match(browser, /renderCell\(row, key, field, 'table'\)/)
  assert.match(browser, /is-cell-on/)
  assert.match(browser, /is-cell-ro/)
  assert.match(browser, /cellFieldWritable/)
  assert.match(browser, /<CellPop/)
  assert.match(browser, /\.fsdb-thumb-btn, \.fsdb-thumb, \.ant-image/)
  assert.doesNotMatch(browser, /skipBoolean/)
})

test('create record sits at the right of the toolbar with a blue label', () => {
  assert.match(browser, /className="fsdb-create-btn"/)
  assert.match(browser, /新建记录/)
  assert.match(browser, /<PlusIcon[\s\S]*新建/)
  assert.doesNotMatch(
    browser,
    /className="tasks-toolbar-left"[\s\S]*?aria-label="新建记录"[\s\S]*?className="tasks-toolbar-right"/,
  )
  const css = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')
  assert.match(css, /\.fsdb-create-btn\{[^}]*border-radius:4px/)
  assert.match(css, /\.fsdb-create-btn\{[^}]*background:var\(--dsw-pick/)
  assert.match(css, /\.fsdb-boolbox\.is-on\{[^}]*background:var\(--dsw-pick/)
  assert.match(css, /\.fsdb-row-check\{[^}]*opacity:0/)
  assert.match(css, /\.fsdb-row-check\{[^}]*position:absolute/)
  assert.match(css, /\.fsdb-row-check\{[^}]*translate\(-100%/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot\{[^}]*width:auto/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot \.tasks-row-tools\{[^}]*position:static/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot \.tasks-row-tools\{[^}]*background:transparent/)
  assert.doesNotMatch(css, /tasks-row-tools-slot \.tasks-row-tools\{[^}]*linear-gradient/)
  assert.match(css, /\.fsdb-page \.tasks-table td:has\(\.fsdb-title-host:focus-within\) \.tasks-row-tools-slot/)
  assert.match(browser, /tasks-row-tools-slot/)
  assert.doesNotMatch(browser, /tasks-title-cell/)
  assert.doesNotMatch(css, /tasks-title-cell/)
  assert.match(css, /tbody tr:hover \.fsdb-row-check/)
  assert.match(css, /td:first-child::before,[\s\S]*th:first-child::before\{[^}]*left:calc\(var\(--fsdb-check-gutter\) \* -1\)/)
  assert.match(css, /\.tasks-table:has\(\.fsdb-row-check\.is-on\) tbody \.fsdb-row-check/)
  assert.match(browser, /function tableBodyRows/)
  assert.match(browser, /markCellOn/)
  assert.doesNotMatch(browser, /<TableBodyRows/)
  assert.match(browser, /index === 0 \? <RowCheck id=\{row\.id\} \/> : null/)
  assert.match(browser, /index === 0 \? <RowCheck ids=\{pickableIds\} \/> : null/)
  const titleFn = browser.slice(browser.indexOf('function RecordTitle'), browser.indexOf('function TableRecordIcon'))
  assert.match(titleFn, /<RecordOpenControls/)
  assert.match(titleFn, /<RecordRowTools/)
  assert.doesNotMatch(titleFn, /<RowCheck/)
  assert.match(css, /\.tasks-minicard-title\{[^}]*font-size:14px/)
  assert.match(css, /\.tasks-minicard-title\{[^}]*font-weight:600/)
  assert.doesNotMatch(css, /fsdb-row-check-cell/)
  assert.match(browser, /persistViewDisplay/)
  assert.match(browser, /withViewDisplay/)
  assert.doesNotMatch(browser, /if \(current\?\.builtin\) return/)
  assert.doesNotMatch(browser, /setColumnKeys\(defaultColumnKeys\(listed\.schema/)
  assert.match(browser, /flattenFacetColumns\(facetCatalog\)/)
  assert.match(browser, /<SchemaFieldEditor/)
  const schemaUi = readFileSync(resolve(import.meta.dirname, './schema-field.tsx'), 'utf8')
  assert.match(schemaUi, /retagSchemaValue\(liveRef.current, resolved\)/)
  assert.doesNotMatch(browser, /<SchemaFieldEditor[\s\S]{0,240}autoOpen/)
  assert.match(readFileSync(resolve(import.meta.dirname, './cell-pop-draft.tsx'), 'utf8'), /autoOpen/)
  assert.match(browser, /schemaTagTone\(flat\.packId\)/)
  assert.match(css, /\.tasks-table\.is-wrap\{[^}]*white-space:normal/)
  assert.match(css, /\.tasks-table th,\.fsdb-page \.tasks-table\.is-wrap th\{[^}]*white-space:nowrap/)
  assert.match(css, /\.tasks-th\{[^}]*white-space:nowrap/)
})

test('filesystem list is table-only; extra modes come from registerView', () => {
  assert.doesNotMatch(browser, /function MiniCard/)
  assert.doesNotMatch(browser, /function QueueRow/)
  assert.doesNotMatch(browser, /mode === 'cards'/)
  assert.doesNotMatch(browser, /mode === 'queue'/)
  assert.doesNotMatch(browser, /mode === 'board'/)
  assert.match(browser, /function RecordRowTools/)
  assert.match(browser, /className="fsdb-title-host"/)
  assert.doesNotMatch(browser, /<th>操作<\/th>/)
  assert.match(browser, /aria-label="查看模式"/)
  assert.doesNotMatch(browser, /extraViews\.length \?/)
})

test('filesystem header expands the shared left sidebar and toggles the right inspector', () => {
  assert.match(browser, /cordis\.sidebar\.collapsed/)
  assert.match(browser, /!viewsOpen \?/)
  assert.match(browser, /data-testid="header-sidebar-expand"/)
  assert.match(browser, /biu:expand-shell-sidebar/)
  assert.match(browser, /data-testid="fsdb-inspector-toggle"/)
  assert.match(browser, /biu:inspector-toggle/)
  assert.match(
    browser,
    /inspectorOpen \?\s*\(\s*<ChevronDoubleRightIcon[\s\S]*:\s*\(\s*<ChevronDoubleLeftIcon/,
  )
})

test('database extras sit after the record detail, not in the inspector', () => {
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const style = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')
  assert.doesNotMatch(page, /biu:inspector-open/)
  assert.match(page, /slots\.place\('inspector-panels'/)
  assert.match(page, /view\?\.inspector/)
  assert.match(page, /seedCollection: path/)
  assert.match(page, /tabLabel: current\?\.view\?\.title/)
  assert.doesNotMatch(page, /tabLabel: '数据库'/)
  assert.doesNotMatch(page, /RecordPanePanel/)
  assert.match(detail, /fsdb-detail-float-nav/)
  assert.match(detail, /按视图顺序切换记录/)
  assert.match(detail, /fsdb-detail-float-btn/)
  assert.match(browser, /findViewNeighbor/)
  assert.match(browser, /stepViewRecord/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*background:#202020/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*width:0/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*translate\(-40px,-50%\)/)
  assert.match(style, /\.fsdb-detail-screen\{[^}]*width:100%/)
  assert.match(style, /\.fsdb-detail-float-btn\{[^}]*width:24px/)
  assert.match(style, /\.fsdb-detail-float-btn\{[^}]*color:#F0EFED/)
  assert.match(style, /\.fsdb-detail-float-btn svg\{[^}]*width:16px/)
  assert.doesNotMatch(style, /border-radius:999px/)
  assert.match(detail, /<h1 className="fsdb-detail-title">/)
  assert.doesNotMatch(detail, /aria-label="删除记录"/)
  assert.doesNotMatch(browser, /onDelete=\{canDelete/)
  assert.match(detail, /<HeadingOutline enabled=\{headingOutline\} \/>/)
  assert.doesNotMatch(browser, /headingOutline=\{collectionPath !== '\/sessions'\}/)
  const outline = readFileSync(resolve(import.meta.dirname, './heading-outline.tsx'), 'utf8')
  assert.match(outline, /closest\('\.fsdb-detail-stage'\)/)
  assert.doesNotMatch(outline, /document\.querySelector\('\.fsdb-detail-main'\)/)
  assert.match(style, /\.heading-outline-host\{[^}]*z-index:20/)
  assert.match(detail, /FOCUS_RECORD_CONTENT/)
  assert.match(detail, /FOCUS_RECORD_TITLE/)
  assert.match(detail, /shouldLeaveTitleForContent/)
  assert.doesNotMatch(detail, /<h2 className="fsdb-detail-title-input">/)
  assert.match(style, /\.fsdb-detail-main\{[^}]*padding:80px 80px 24px/)
  assert.match(style, /\.fsdb-main > \.fsdb-detail-title-row\{[^}]*flex:none/)
  assert.match(style, /\.fsdb-main\{[^}]*padding:80px 80px 16px/)
  assert.match(style, /\.fsdb-main\{[^}]*max-width:var\(--dsw-chat-max-width\)/)
  assert.match(style, /\.fsdb-detail-main\{[^}]*max-width:var\(--dsw-chat-max-width\)/)
  assert.match(style, /\.fsdb-detail-title\{[^}]*font-size:32px/)
  assert.match(browser, /<h1 className="fsdb-detail-title">\{activeView\?\.name \?\? title\}<\/h1>/)
  assert.match(style, /\.fsdb-detail-title-row\{[^}]*padding-bottom:16px/)
  assert.match(browser, /<TableGlyph icon=\{currentTable\?\.view\?\.icon\}/)
  assert.match(detail, /<DetailTitleIcon/)
  assert.match(detail, /recordPreviewEmoji\(selected\)/)
  assert.match(detail, /Icon=\{chrome\?\.Icon\}/)
  assert.match(detail, /<Icon record=\{record\} \/>/)
  assert.match(detail, /writePatch\(selected, \{ emoji: next \}\)/)
  assert.match(detail, /fsdb:change/)
  assert.match(browser, /<RecordMark/)
  assert.match(browser, /tableIcon=\{currentTable\?\.view\?\.icon\}/)
  assert.match(browser, /function TableRecordIcon/)
  assert.match(browser, /<RecordEmojiBoard/)
  assert.match(browser, /writePatch\(row, \{ emoji: normalizeRecordEmoji\(next\) \}\)/)
  assert.match(detail, /data-testid=\{`fsdb-pane-\$\{pane\.id\}`\}/)
  assert.match(style, /\.fsdb-fileview\{[^}]*min-height:0/)
  assert.match(style, /\.fsdb-fileview\{[^}]*max-height:none/)
  assert.match(style, /\.fsdb-fileview\{[^}]*overflow:visible/)
  assert.match(style, /\.fsdb-fileview-pre\{[^}]*overflow:visible/)
  assert.match(style, /\.fsdb-fileview-pre\{[^}]*max-height:none/)
  assert.match(style, /\.fsdb-fileview-img\{[^}]*max-height:none/)
  assert.match(style, /\.fsdb-right-body\{[^}]*overflow:auto/)
  assert.match(browser, /app-pane-in/)
  assert.doesNotMatch(browser, /nested \? undefined : 'app-pane-in'/)
  assert.match(browser, /key=\{nested \? 'embed' : `\$\{collectionPath\}:\$\{detailId \?\? ''\}`\}/)
  assert.match(style, /\.fsdb-detail-split\{[^}]*overflow:visible/)
  assert.doesNotMatch(style, /\.fsdb-fileview-pre\{[^}]*overflow:auto/)
  assert.doesNotMatch(style, /\.fsdb-fileview\{[^}]*min-height:240px/)
  assert.doesNotMatch(style, /\.fsdb-fileview-img\{[^}]*max-height:420px/)
  assert.match(browser, /embed \?/)
  assert.doesNotMatch(browser, /setRecordFocus/)
})

test('inspector embed does not poll the collection every 20s', () => {
  assert.match(browser, /const timer = nested/)
  assert.match(browser, /}, 20000\)/)
})

test('switching tables does not remount the whole browser', () => {
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.doesNotMatch(page, /key=\{currentPath\}/)
})

test('list polling pauses while a record is open', () => {
  assert.match(browser, /if \(detailIdRef\.current\) return/)
  assert.match(browser, /}, 20000\)/)
})

test('open detail still reloads body when the collection changes', () => {
  assert.match(browser, /if \(detailIdRef\.current\) pullDetailBody/)
  assert.match(browser, /window.dispatchEvent\(new Event\('fsdb:change'\)\)/)
})

test('collection reload does not follow callback identity', () => {
  assert.match(browser, /const reloadKey = /)
  assert.match(browser, /void reloadRef\.current\(\)/)
  assert.doesNotMatch(browser, /void reload\(\)\s*\n\s*\}, \[reload\]/)
  assert.match(browser, /const EMPTY_FILTERS/)
  assert.doesNotMatch(browser, /lockedFilters = \{\}/)
  assert.match(browser, /void pullFacets\(\)/)
  assert.doesNotMatch(browser, /pullFacets\(\),\s*\n\s*\]\)/)
})

test('pager keeps the current page when filter objects are only recreated', () => {
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const inspector = readFileSync(resolve(import.meta.dirname, './inspector-database.tsx'), 'utf8')
  assert.match(browser, /const queryFiltersKey = JSON.stringify\(queryFilters\)/)
  assert.match(browser, /\[fetchQuery, queryFiltersKey, sortField, sortDir, pageSize, collectionPath, dataPath\]/)
  assert.doesNotMatch(browser, /\[fetchQuery, queryFilters, sortField/)
  assert.match(browser, /tables\s*\n\s*\.map\(\(table\) => table\.path\)/)
  assert.doesNotMatch(browser, /tablePathsKey = tables\.map/)
  assert.match(page, /lockedFiltersFromSearch\?\.\(location\.search\) \?\? EMPTY_FILTERS/)
  assert.doesNotMatch(page, /lockedFiltersFromSearch\?\.\(location\.search\) \?\? \{\}/)
  assert.match(inspector, /lockedFiltersFromSearch\?\.\(search\) \?\? EMPTY_FILTERS/)
  assert.doesNotMatch(inspector, /lockedFiltersFromSearch\?\.\(search\) \?\? \{\}/)
})

test('page collection uses a document glyph, not the table/database icon', () => {
  const glyphs = readFileSync(resolve(import.meta.dirname, './table-glyph.tsx'), 'utf8')
  assert.match(glyphs, /name === 'document' \|\| name === 'document-text' \|\| name === 'page'/)
  assert.match(glyphs, /<DocumentIcon/)
})

test('boolean field glyph is a checkbox, not the document list icon', () => {
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  assert.match(cells, /kind === 'boolean'\) return <span aria-hidden className="fsdb-field-bool-glyph"><BoolBox on=\{false\}/)
  assert.doesNotMatch(cells, /kind === 'boolean'\) return <ClipboardDocumentListIcon/)
})

test('facet field glyph matches the collection stack icon', () => {
  const glyphs = readFileSync(resolve(import.meta.dirname, './table-glyph.tsx'), 'utf8')
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  const spec = readFileSync(resolve(import.meta.dirname, '../host/facets-collection.ts'), 'utf8')
  assert.match(spec, /icon: 'rectangle-stack'/)
  assert.match(glyphs, /name === 'rectangle-stack'/)
  assert.match(glyphs, /<RectangleStackIcon/)
  assert.match(cells, /kind === 'facet'\) return <RectangleStackIcon/)
  assert.doesNotMatch(cells, /kind === 'facet'\) return <TagIcon/)
})

test('row actions reload even when updatedAt is unchanged', () => {
  assert.match(browser, /function recordsFingerprint\(rows/)
  assert.match(browser, /return JSON.stringify\(rows\)/)
  assert.match(browser, /quietUntil\.current = 0\s*\n\s*await reload\(\)/)
})

test('row actions hover the registered action label', () => {
  assert.match(browser, /data-dock-tip=\{action\.label\}/)
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  assert.match(cells, /data-dock-tip=\{label\}/)
  const plugin = readFileSync(resolve(import.meta.dirname, '../../../core-plugin-system/src/web/chrome.tsx'), 'utf8')
  assert.match(plugin, /data-dock-tip=\{action\.label\}/)
})

test('inspector no longer listens for add/copy view actions', () => {
  assert.doesNotMatch(browser, /biu:inspector-action/)
  assert.doesNotMatch(browser, /detail === 'add-view'/)
  assert.doesNotMatch(browser, /detail === 'copy-view'/)
})

test('database inspector tab has a close control beside crumb expand', () => {
  const tab = readFileSync(resolve(import.meta.dirname, './inspector-database.tsx'), 'utf8')
  assert.match(tab, /onClose\?: \(\) => void/)
  assert.match(tab, /data-testid="inspector-tab-close"/)
  assert.match(tab, /inspector-crumb-close/)
  assert.match(tab, /XMarkIcon/)
  assert.match(tab, /inspector-crumb-actions/)
  assert.match(tab, /data-testid="inspector-crumb-toggle"/)
  assert.match(tab, /is-agent-working/)
  assert.match(tab, /fsdb-agent-follow/)
  assert.match(tab, /key=\{inspectorPath\}/)
})

test('inspector crumbs lock the first level to an icon', () => {
  const tab = readFileSync(resolve(import.meta.dirname, './inspector-database.tsx'), 'utf8')
  const trail = readFileSync(resolve(import.meta.dirname, './crumb-trail.tsx'), 'utf8')
  const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
  assert.match(tab, /lockRootCrumb/)
  assert.match(trail, /lockRootCrumb/)
  assert.match(trail, /rootLocked/)
  assert.match(trail, /fsdb-crumb-btn is-static/)
  assert.match(trail, /lockRootCrumb && index === 1/)
  assert.doesNotMatch(browser, /lockRootCrumb/)
})

test('collection header has a layout config control next to the star', () => {
  assert.match(browser, /data-testid="fsdb-layout-toggle"/)
  assert.match(browser, /data-testid="fsdb-layout-menu"/)
  assert.match(browser, /data-testid="fsdb-layout-max"/)
  assert.match(browser, /data-testid="fsdb-layout-full"/)
  assert.match(browser, /AdjustmentsHorizontalIcon/)
  assert.match(browser, /persistPageWidth\('full'\)/)
  assert.match(browser, /is-full-width/)
})
