import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

const css = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')

test('list and detail share the chat column max width with side padding', () => {
  assert.match(css, /\.fsdb-main\{[^}]*max-width:var\(--dsw-chat-max-width\)/)
  assert.match(css, /\.fsdb-main\{[^}]*margin-inline:auto/)
  assert.match(css, /\.fsdb-main\{[^}]*padding:80px 80px 16px/)
  assert.match(css, /\.fsdb-main > \.fsdb-detail-title-row\{[^}]*flex:none/)
  assert.match(css, /\.fsdb-detail-title-row\{[^}]*padding-bottom:16px/)
  assert.match(css, /\.fsdb-detail-main\{[^}]*max-width:var\(--dsw-chat-max-width\)/)
  assert.match(css, /\.fsdb-detail-main\{[^}]*margin-inline:auto/)
  assert.match(css, /\.fsdb-detail-main\{[^}]*padding:80px 80px 24px/)
  assert.doesNotMatch(css, /\.fsdb-main\{[^}]*max-width:none/)
  assert.match(css, /\.fsdb-page\.is-full-width \.fsdb-main,\.fsdb-page\.is-full-width \.fsdb-detail-main\{[^}]*max-width:none/)
  assert.doesNotMatch(css, /\.fsdb-page\.is-full-width[^{]*\{[^}]*padding:[^}]*24px/)
  assert.doesNotMatch(css, /flex:0 0 36%/)
  assert.match(css, /\.fsdb-page\{[^}]*--fsdb-check-gutter:26px/)
  assert.match(css, /\.fsdb-page \.tasks-table td:has\(\.fsdb-title-host\)\{[^}]*position:relative/)
  assert.doesNotMatch(css, /\.fsdb-page \.tasks-table td:has\(\.fsdb-title-host\)\{[^}]*padding-right:var\(--fsdb-row-tools-w\)/)
  assert.match(css, /\.fsdb-page \.tasks-title-aside\{[^}]*display:inline-flex/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot\{[^}]*display:inline-flex/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot\{[^}]*right:8px/)
  assert.match(css, /\.fsdb-page \.tasks-table th\{[^}]*z-index:5/)
  assert.match(css, /\.fsdb-page \.tasks-table tbody tr:hover\{[^}]*z-index:6/)
  assert.match(css, /\.fsdb-page \.tasks-table \[data-dock-tip\]::after\{[^}]*z-index:80/)
  assert.match(css, /\.fsdb-page \.tasks-table-wrap\{[^}]*padding-left:var\(--fsdb-check-gutter\)/)
  assert.doesNotMatch(css, /\.inspector-database-page \.fsdb-main,\.inspector-database-page \.fsdb-detail-main\{[^}]*padding-left:28px/)
  assert.doesNotMatch(css, /inspector-database-page[^{]*\{[^}]*padding-left:28px/)
  assert.match(css, /\.fsdb-page \.tasks-table\.is-wrap\.is-truncate \.fsdb-title-text\{[^}]*-webkit-line-clamp:2/)
  assert.match(css, /\.fsdb-page \.tasks-table\.is-wrap\.is-truncate \.fsdb-cell\{[^}]*max-height:2\.8em/)
  assert.doesNotMatch(css, /\.tasks-table\.is-wrap\.is-truncate \.fsdb-cell\{[^}]*display:-webkit-box/)
  assert.doesNotMatch(css, /max-width:min\(42%,22rem\)/)
  assert.match(css, /\.fsdb-page \.tasks-group-fold \.sidebar-group-fold-chevron[\s\S]*display:grid/)
  assert.match(css, /\.fsdb-page \.tasks-group-fold:hover \.sidebar-group-fold-face[\s\S]*display:grid/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot\{[^}]*width:auto/)
  assert.match(css, /\.fsdb-page \.fsdb-title-host\{[^}]*overflow:hidden/)
  assert.match(css, /\.fsdb-page \.fsdb-proplist \.fsdb-proprow\{[^}]*display:inline-flex/)
  assert.doesNotMatch(css, /\.fsdb-proplist \.fsdb-proprow\{[^}]*grid-template-columns:max-content minmax\(0,1fr\)/)
  assert.match(css, /\.tasks-viewdd-menu\{[^}]*min-width:320px/)
  assert.match(css, /\.tasks-viewtabs\{[^}]*overflow:hidden/)
  assert.match(css, /\.tasks-viewdd-item-actions\{[^}]*visibility:hidden/)
  assert.match(css, /\.tasks-viewdd-act\{[^}]*width:26px/)
  assert.match(css, /\.fsdb-right-body:has\(\.fsdb-detail-stage\) \.app-pane-in\{[^}]*overflow:visible/)
  assert.match(css, /\.fsdb-right-body:has\(\.fsdb-detail-stage\) \.app-pane-in\{[^}]*width:100%/)
  assert.match(css, /\.fsdb-right-body:has\(\.fsdb-pager\)\{[^}]*overflow:hidden/)
  assert.match(css, /\.fsdb-pager\{[^}]*margin-top:auto/)
  assert.match(css, /\.fsdb-page\{[^}]*--fsdb-pager-lift:calc\(1rem \+ 44px \+ 25px \+ 25px - 30px\)/)
  assert.match(css, /\.inspector-database-page \.fsdb-pager\{[^}]*var\(--fsdb-pager-lift\)/)
  assert.match(css, /\.fsdb-page \.tasks-table\{[^}]*border-left:0|border:0/)
  assert.match(css, /\.fsdb-page \.tasks-table th,\.fsdb-page \.tasks-table td\{[^}]*border-right:1px solid color-mix\(in srgb,var\(--dsw-border\) 80%,transparent\)/)
  assert.match(css, /\.fsdb-page \.tasks-table th:last-child,\.fsdb-page \.tasks-table td:last-child\{[^}]*border-right:0/)
})

test('title cell hover icons use F0EFED', () => {
  assert.match(css, /\.fsdb-page \.tasks-title-open\{[^}]*color:#F0EFED/)
  assert.match(css, /\.fsdb-page \.tasks-title-open:hover\{[^}]*color:#F0EFED/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools \.tasks-icon-btn,\.fsdb-page \.tasks-row-actions \.tasks-icon-btn\{[^}]*color:#F0EFED/)
})

test('list properties keep muted colors; detail property column uses ACA9A4 keys and F0EFED values', () => {
  assert.match(css, /\.fsdb-proprow-k,\.fsdb-prop>span:first-child\{[^}]*color:#7B7B79/)
  assert.match(css, /\.fsdb-proprow-v,\.fsdb-prop-val,\.fsdb-detail-id\{[^}]*color:#7C7A76/)
  assert.match(css, /\.fsdb-schema-prop-k\{[^}]*color:#7B7B79/)
  assert.match(css, /\.fsdb-proprow-k svg,\.fsdb-prop>span:first-child svg,\.fsdb-schema-prop-k svg\{[^}]*color:#F0EFED/)
  assert.match(css, /\.fsdb-detail-aside \.fsdb-proprow-k,\.fsdb-detail-aside \.fsdb-prop>span:first-child,\.fsdb-detail-aside \.fsdb-proprow-label\{[^}]*color:#ACA9A4/)
  assert.match(css, /\.fsdb-detail-aside \.fsdb-proprow-k svg,\.fsdb-detail-aside \.fsdb-prop>span:first-child svg\{[^}]*color:#ACA9A4/)
  assert.match(css, /\.fsdb-detail-aside \.fsdb-proprow-v,\.fsdb-detail-aside \.fsdb-prop-val,\.fsdb-detail-aside \.fsdb-detail-id,\.fsdb-detail-aside \.fsdb-plain-input\{[^}]*color:#F0EFED/)
})

test('usage figures in collection cells match the table font size', () => {
  assert.match(css, /\.fsdb-page \.fsdb-cell \.traj-usage,\.fsdb-page \.fsdb-cell \.traj-usage-empty,\.fsdb-page \.tasks-table \.traj-usage,\.fsdb-page \.tasks-table \.traj-usage-empty\{[^}]*font-size:14px/)
  assert.match(css, /\.fsdb-page \.chat-pane \.traj-usage,\.fsdb-page \.chat-pane \.traj-usage-empty\{[^}]*font-size:var\(--dsw-chat-ui-font-size\)/)
})

test('visible column menu scrolls inside a max height', () => {
  const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
  assert.match(browser, /className="tasks-sort-menu fsdb-col-menu"/)
  assert.match(browser, /className="fsdb-col-menu-list"/)
  assert.match(css, /\.fsdb-page \.fsdb-col-menu\{[^}]*max-height:min\(60vh,360px\)/)
  assert.match(css, /\.fsdb-page \.fsdb-col-menu-list\{[^}]*overflow:auto/)
})

test('table column widths can be dragged and saved on the view', () => {
  const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
  assert.match(browser, /data-testid="fsdb-col-resizer"/)
  assert.match(browser, /startColResize/)
  assert.match(browser, /columnWidths/)
  assert.match(browser, /persistViews/)
  assert.match(css, /\.fsdb-page \.tasks-table\.is-cols-fixed\{[^}]*table-layout:fixed/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer\{[^}]*cursor:col-resize/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer\{[^}]*top:0/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer\{[^}]*bottom:0/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer\{[^}]*right:-5px/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer::after\{[^}]*left:50%/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer::after\{[^}]*width:4px/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer::after\{[^}]*top:0/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer::after\{[^}]*bottom:0/)
  assert.match(css, /\.fsdb-page \.tasks-table \.fsdb-col-resizer:hover::after,\.fsdb-page \.tasks-table \.fsdb-col-resizer\.is-active::after\{[^}]*background:var\(--dsw-pick/)
  assert.doesNotMatch(css, /\.fsdb-col-resizer:hover::after[^{]*\{[^}]*--dsw-business/)
})
